### ISSUE TITLE
Missing plane icons 

### ISSUE THREAD

**Issue by Biggus-Geeus** [mikenye/docker-virtualradarserver#2]
I have an issue where I don't see any plane icons or altitude stalks on the map.
This happens on the desktop or mobile site, I have tried a variety of browsers.
This forum [https://forum.virtualradarserver.com/viewtopic.php?t=1957](https://forum.virtualradarserver.com/viewtopic.php?t=1957) details the same problem I am having and mentions the version of mono is causing the problem.
Can you investigate please.

**Comment by mikenye** [comment]
Hi @Biggus-Geeus, sorry for the delay in acknowledging this, I missed the alert from GitHub.

I'm looking into this now.

**Comment by mikenye** [comment]
Thanks for the forum link, that was helpful. I've changed the container from `mono:6` to `debian:stable-slim` and am installing mono version 6.0.0.334 as-per the forum post. This appears to have solved the issue.

![image](https://user-images.githubusercontent.com/6915079/80170544-c3c59900-861a-11ea-9b55-463f05531dfd.png)

I'll update the `development` tag, and if you could test and report back it would be greatly appreciated.

**Comment by mikenye** [comment]
OK, image `mikenye/virtualradarserver:development` should be ready for you to try out. Please let me know if this fixes your issue.

**Comment by Biggus-Geeus** [comment]
Hi,
That is working perfectly, it also fixed the issue with showing the silhouettes, operator flags on android browsers and showing pictures on all browsers.  Thanks for fixing this :-)

**Comment by mikenye** [comment]
The fix is now in `latest` and `2.4.4.36598` tags.

Thanks for reporting this and making it easy to fix.
